### PR TITLE
Fix #191 and #188

### LINKED ISSUE #191: Error when `supportsPagination` advanced query option is `FALSE`
**Describe the bug**

I stumbled across a URL that errors when the supportsPagination advanced query option is `FALSE`. Unsure why the server is set up this way or if this worked with earlier versions of arcgislayers or arcgisutils.

**To Reproduce**

``` r
library(arcgislayers)

url <- "https://geodata.baltimorecity.gov/egis/rest/services/Planning/Bike_Master_Plan/MapServer/3"

layer <- arc_open(url)

arc_select(layer)
#> Warning in arc_select(layer): Status code: 400
#> Error: Pagination is not supported.
#> Error in `rlang::set_names()`:
#> ! `x` must be a vector
```

<sup>Created on 2024-06-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Expected behavior**

Expect selecting the data to be allowed even if pagination is not permitted. If not, a more informative error message would be helpful.

### PR DESCRIPTION
**Pull request by elipousson**
## Checklist 

- [X] update NEWS.md
- [X] documentation updated with `devtools::document()`
- [-] `devtools::check()` passes locally

## Changes 

Fixes  #191 by adding a helper function (`get_query_resps()`) that handles layers that don't support pagination by using a standard query request.

Also fixes the CRS bug #188 using a similar approach as the esri2sf package.

**Issues that this closes** 

Fix #191 and #188

## Follow up tasks

None identified.

### CODE REVIEW

File: R/sf-methods.R [hunk 1]
```diff
@@ -1,11 +1,22 @@
-
 # st_crs method for feature layer
 st_crs.FeatureLayer <- function(obj, ...) {
-  sf::st_crs(obj[["extent"]][["spatialReference"]][["latestWkid"]])
+  spatialReference <- obj[["extent"]][["spatialReference"]]
+
+  obj_crs <- spatialReference[["latestWkid"]] %||%
+    spatialReference[["wkid"]] %||%
+    spatialReference[["wkt"]]
```
Comment (JosiahParry) [inline R/sf-methods.R:7]: Yah, this is needed! Thank you. Think we can generalize this for both FeatureLayer and ImageServer? Something like

```r
arc_sr_to_crs <- function(obj) {
spatialReference <- obj[["extent"]][["spatialReference"]]

  obj_crs <- spatialReference[["latestWkid"]] %||%
    spatialReference[["wkid"]] %||%
    spatialReference[["wkt"]]

  sf::st_crs(obj_crs)
}
```

File: R/arc-select.R [hunk 2]
```diff
@@ -264,6 +258,67 @@ collect_layer <- function(
...
+
+    # If url is more than 2048 characters long, add the query to the
+    # body of the request
+    if (nchar(req_query[["url"]]) > 2048) {
+      req_query <- rlang::exec(
+        httr2::req_body_form,
+        .req = req,
+        !!!query_params
+      )
+    }
```
Comment (JosiahParry) [inline R/arc-select.R:294]: I think we should always prefer using form body here. is there any reason to prefer a get request here?

File: R/sf-methods.R (hunk 1 above)
Comment (elipousson) [reply R/sf-methods.R:7]: Works for me – we'd need to replace calls some of the internal calls to st_crs since wherever it is currently using the S3 method. Maybe `arc_sr_as_crs()` to stay similar to all the `sf::st_as_` functions?

Comment (JosiahParry) [reply R/sf-methods.R:7]: Oh! To be even clearer: I think we should _keep the `sf::st_crs()`_ methods. But the methods should just call the `arc_sr_as_crs()` function since the body is identical in both cases

Comment (elipousson) [reply R/sf-methods.R:7]: Would you want to call `sf::st_crs` or `arc_sr_as_crs()` internally? Assuming you'd want to keep the default crs values the same, e.g. `crs = sf::st_crs(x)`.

**Comment by JosiahParry** [comment]
Thank you @elipousson! I pushed a single change that just adds comments to the function so that I can remember what is happening inside this function later. 

Once CI is green ill smash merge

**Comment by JosiahParry** [comment]
Windows is failing entirely illegibly. That can be a me problem at a later date. Thank you so much!
