### PR TITLE
Fix #175

### LINKED ISSUE #175: FeatureLayer's return fields when none provided
**Describe the bug**
FeatureLayers will return additional fields when none are specified. This is not a bug necessarily, as this is how feature services work. 

For example this query returns the `NAME` field even though no fields were specified `https://services.arcgis.com/P3ePLMYs2RVChkJx/ArcGIS/rest/services/USA_Major_Cities_/FeatureServer/0/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&relationParam=&returnGeodetic=false&outFields=&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&defaultSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=`

**To Reproduce**

``` r
library(arcgis)
#> Attaching core arcgis packages:
#> → arcgisutils v0.2.0.9000
#> → arcgislayers v0.2.0

flayer <- arc_open("https://services.arcgis.com/P3ePLMYs2RVChkJx/ArcGIS/rest/services/USA_Counties_Generalized_Boundaries/FeatureServer/0")

arc_select(flayer, fields = "")
#> Simple feature collection with 3143 features and 2 fields
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -178.2176 ymin: 18.92179 xmax: -66.96927 ymax: 71.40624
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>               NAME OBJECTID                       geometry
#> 1   Autauga County        1 MULTIPOLYGON (((-86.82067 3...
#> 2   Baldwin County        2 MULTIPOLYGON (((-87.97309 3...
#> 3   Barbour County        3 MULTIPOLYGON (((-85.74337 3...
#> 4      Bibb County        4 MULTIPOLYGON (((-87.41986 3...
#> 5    Blount County        5 MULTIPOLYGON (((-86.96799 3...
#> 6   Bullock County        6 MULTIPOLYGON (((-85.4114 32...
#> 7    Butler County        7 MULTIPOLYGON (((-86.44912 3...
#> 8   Calhoun County        8 MULTIPOLYGON (((-85.79353 3...
#> 9  Chambers County        9 MULTIPOLYGON (((-85.58963 3...
#> 10 Cherokee County       10 MULTIPOLYGON (((-85.41657 3...
```

<sup>Created on 2024-03-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Expected behavior**

When no fields are specified, only geometry should be returned. 

**Additional context**

Addressed in https://github.com/R-ArcGIS/arcgislayers/pull/167

### PR DESCRIPTION
**Pull request by elipousson**
Also implement new `rbind_results()` function added w/ https://github.com/R-ArcGIS/arcgisutils/issues/38

## Changes 

Per the discussion in draft PR: https://github.com/R-ArcGIS/arcgislayers/pull/167 this PR fixes an issue w/ returning fields not specified in fields argument and 

**Issues that this closes** 

#175

## Follow up tasks

Additional changes as described in draft PR.

### CODE REVIEW

File: R/arc-select.R [hunk 1]
```diff
@@ -461,3 +479,26 @@ count_results <- function(req, query) {
...
+#'
+#' [validate_fields()] ensures that fields passed to [arc_select()] match
+#' permissible values.
+#'
+#' @keywords internal
+#' @noRd
+match_fields <- function(fields, values = NULL, multiple = TRUE, error_call = rlang::caller_env()) {
+  if (is.null(fields) || identical(fields, "*")) {
+    return(fields)
+  }
```
Comment (JosiahParry) [inline R/arc-select.R:492]:
```suggestion
#' Match fields
#'
#' [match_fields()] ensures that fields passed to [arc_select()] match
#' permissible values.
#'
#' @keywords internal
#' @noRd
match_fields <- function(fields, values = NULL, multiple = TRUE, error_call = rlang::caller_env()) {
  if (is.null(fields) || identical(fields, "*")) {
    return(fields)
  }
```

What is returned if the if statement is evaluated to `TRUE` should `fields` should be returned?

**Comment by JosiahParry** [comment]
This is super clear! Thank you! 

We should add some tests here: 

1. what happens when we return no fields? `fields = ""`
2. testing that when we have specified fields e.g `fields = c("a", "b")`
3. fields _with_ objectid specified
4. using fields with a Table.


@elipousson if youre comfortable with me pushing to your branch I could write the tests

**Comment by elipousson** [comment]
Caught one more issue - I forgot to remove the existing check for fields that was expecting a scalar input. All good now, I think.

File: R/arc-select.R [hunk 2]
```diff
@@ -107,29 +105,16 @@ arc_select <- function(
...
-      )
-    }
-    # collapse together
-    fields <- paste0(fields, collapse = ",")
-  }
+  fields <- fields %||% query[["outFields"]]
+
+  fields <- match_fields(
+    fields = fields,
+    values = c(x[["fields"]][["name"]], "")
```
Comment (JosiahParry) [inline R/arc-select.R:112]: @elipousson this is the only change I made. This will allow users to return only geometry if they so choose.
